import React, { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { RingColors } from '@/constants/theme';
import { useRingData } from '@/context/RingDataContext';
import { ActionButton, Card, Header, Metric, Page, ProgressBar, ScoreGauge, SectionTitle, Sparkline, styles } from '@/components/RingUI';

function DevicePill() { const { connected, battery, findMyRing, isGuestMode, setIsGuestMode, isMeasuring, measureNow } = useRingData(); return <View style={dashboardStyles.dashboardActions}><Pressable onPress={findMyRing} style={styles.devicePill}><View style={[styles.deviceDot, { backgroundColor: connected ? RingColors.recovery : RingColors.muted }]} /><Text style={styles.deviceText}>{battery}%</Text><Ionicons name="flash" size={13} color={RingColors.warning} /></Pressable><View style={dashboardStyles.guestControl}><Text style={dashboardStyles.guestLabel}>Guest Mode</Text><Switch value={isGuestMode} onValueChange={setIsGuestMode} trackColor={{ false: RingColors.border, true: RingColors.warning }} thumbColor={RingColors.text} /></View><Pressable accessibilityRole="button" accessibilityState={{ busy: isMeasuring }} disabled={isMeasuring} onPress={measureNow} style={[dashboardStyles.measureAction, isMeasuring && dashboardStyles.measureActionDisabled]}><Ionicons name={isMeasuring ? 'pulse' : 'refresh-outline'} size={15} color={RingColors.text} /><Text style={dashboardStyles.measureActionText}>{isMeasuring ? 'Measuring...' : 'Measure Now'}</Text></Pressable>{isGuestMode && <Text style={dashboardStyles.guestBanner}>Guest Active</Text>}</View>; }

const dashboardStyles = StyleSheet.create({
	dashboardActions: { alignItems: 'flex-end', gap: 8 },
	guestControl: { alignItems: 'center', flexDirection: 'row', gap: 6 },
	guestLabel: { color: RingColors.text, fontSize: 12, fontWeight: '700' },
	measureAction: { alignItems: 'center', backgroundColor: RingColors.sleep, borderRadius: 8, flexDirection: 'row', gap: 5, paddingHorizontal: 10, paddingVertical: 7 },
	measureActionDisabled: { opacity: 0.7 },
	measureActionText: { color: RingColors.background, fontSize: 12, fontWeight: '800' },
	guestBanner: { backgroundColor: '#4A2A08', borderRadius: 8, color: RingColors.warning, fontSize: 12, fontWeight: '800', paddingHorizontal: 10, paddingVertical: 6 },
});

export function HomeScreen() { const { vitals, heartRateHistory } = useRingData(); return <Page><Header eyebrow="Friday, August 21" title="RingPulse" action={<DevicePill />} /><Text style={styles.greeting}>Your body is ready for a focused day.</Text><View style={styles.gaugeRow}><Card style={styles.gaugeCard}><ScoreGauge value={78} label="Recovery" color={RingColors.recovery} /><Text style={styles.scoreHint}>Good readiness</Text></Card><Card style={styles.gaugeCard}><ScoreGauge value={64} label="Sleep" color={RingColors.sleep} /><Text style={styles.scoreHint}>7h 42m in bed</Text></Card><Card style={styles.gaugeCard}><ScoreGauge value={42} label="Strain" color={RingColors.strain} /><Text style={styles.scoreHint}>8.8 of 21</Text></Card></View><SectionTitle>Live vitals <Text style={styles.live}>● LIVE</Text></SectionTitle><Card><View style={styles.metricRow}><Metric label="Heart rate" value={vitals.heartRate ?? '--'} unit=" BPM" color={RingColors.danger} /><Metric label="Blood oxygen" value={vitals.spo2 ?? '--'} unit="%" color={RingColors.strain} /><Metric label="Temperature" value={vitals.temp ?? '--'} unit="°C" color={RingColors.warning} /></View><View style={styles.divider} /><View style={styles.metricRow}><Metric label="Steps today" value="4,230" unit=" steps" color={RingColors.text} /><Metric label="HRV (RMSSD)" value={vitals.hrv ?? '--'} unit=" ms" color={RingColors.recovery} /><Metric label="Respiration" value="15.2" unit=" rpm" color={RingColors.sleep} /></View></Card><SectionTitle>Heart rate trend <Text style={styles.detail}>last 20 readings</Text></SectionTitle><Card><Sparkline data={heartRateHistory} color={RingColors.danger} /><View style={styles.chartFooter}><Text style={styles.detail}>62 BPM low</Text><Text style={styles.detail}>now {vitals.heartRate ?? '--'} BPM</Text></View></Card><ActionButton label="Log your day" icon="add-circle-outline" tone={RingColors.protein} /></Page>; }

export function SleepScreen() { return <Page><Header eyebrow="Sleep lab" title="Sleep & recovery" /><Card><View style={styles.summaryRow}><View><Text style={styles.cardKicker}>SLEEP PERFORMANCE</Text><Text style={styles.heroMetric}>92<Text style={styles.heroUnit}>%</Text></Text><Text style={styles.detail}>7h 42m asleep of 8h 20m need</Text></View><ScoreGauge value={92} label="Optimal" color={RingColors.sleep} /></View></Card><SectionTitle>Sleep stages <Text style={styles.detail}>last night</Text></SectionTitle><Card><ProgressBar segments={[{ label: 'Deep', value: 24, color: RingColors.sleep }, { label: 'Light', value: 46, color: RingColors.strain }, { label: 'REM', value: 22, color: RingColors.protein }, { label: 'Awake', value: 8, color: RingColors.muted }]} /></Card><SectionTitle>Overnight analytics</SectionTitle><Card><Text style={styles.cardKicker}>HRV TREND · RMSSD</Text><Sparkline data={[42, 48, 45, 52, 58, 53, 61, 66, 62, 70, 65, 72]} color={RingColors.sleep} /><View style={styles.metricRow}><Metric label="Resting heart rate" value="52" unit=" BPM" color={RingColors.recovery} /><Metric label="Respiratory rate" value="15.2" unit=" rpm" color={RingColors.sleep} /><Metric label="Avg HRV" value="61" unit=" ms" color={RingColors.strain} /></View></Card></Page>; }

export function StrainScreen() { const { workoutActive, startWorkout, stopWorkout, heartRateHistory, vitals } = useRingData(); return <Page><Header eyebrow="Performance" title="Strain & workouts" /><Card><View style={styles.strainTop}><View><Text style={styles.cardKicker}>DAILY STRAIN</Text><Text style={[styles.heroMetric, { color: RingColors.strain }]}>8.8<Text style={styles.heroUnit}> / 21</Text></Text><Text style={styles.detail}>Moderate exertion today</Text></View><Ionicons name="flash-outline" size={42} color={RingColors.strain} /></View><View style={styles.strainTrack}><View style={[styles.strainFill, { width: '42%' }]} /></View><View style={styles.chartFooter}><Text style={styles.detail}>Rest</Text><Text style={styles.detail}>Peak</Text></View></Card><SectionTitle>Heart rate zones <Text style={styles.detail}>100 active minutes</Text></SectionTitle><Card><View style={styles.zoneRow}><View style={styles.zone}><View style={styles.barTrack}><View style={[styles.bar, { height: '76%', backgroundColor: RingColors.muted }]} /></View><Text style={styles.zoneLabel}>Z1</Text><Text style={styles.zoneValue}>38m</Text></View><View style={styles.zone}><View style={styles.barTrack}><View style={[styles.bar, { height: '60%', backgroundColor: RingColors.strain }]} /></View><Text style={styles.zoneLabel}>Z2</Text><Text style={styles.zoneValue}>30m</Text></View><View style={styles.zone}><View style={styles.barTrack}><View style={[styles.bar, { height: '40%', backgroundColor: RingColors.warning }]} /></View><Text style={styles.zoneLabel}>Z3</Text><Text style={styles.zoneValue}>20m</Text></View><View style={styles.zone}><View style={styles.barTrack}><View style={[styles.bar, { height: '24%', backgroundColor: RingColors.danger }]} /></View><Text style={styles.zoneLabel}>Z4/5</Text><Text style={styles.zoneValue}>12m</Text></View></View></Card><SectionTitle>{workoutActive ? 'Workout in progress' : 'Sport mode'}</SectionTitle><Card><View style={styles.workoutRow}><View><Text style={styles.heroMetric}>{workoutActive ? '18:42' : 'Ready'}</Text><Text style={styles.detail}>{workoutActive ? `${vitals.heartRate ?? '--'} BPM · 184 kcal` : 'Fast 1-second sampling'}</Text></View><ActionButton label={workoutActive ? 'End workout' : 'Start workout'} icon={workoutActive ? 'stop-circle-outline' : 'play-circle-outline'} onPress={workoutActive ? stopWorkout : startWorkout} tone={workoutActive ? RingColors.danger : RingColors.strain} /></View>{workoutActive && <Sparkline data={heartRateHistory} color={RingColors.strain} />}</Card></Page>; }

export function JournalScreen() { const [habits, setHabits] = useState([true, true, false]); const toggle = (index: number) => setHabits((items) => items.map((value, itemIndex) => itemIndex === index ? !value : value)); const labels = [['Protein intake', 'More than 50g today', RingColors.protein], ['Physical training', 'Workout completed', RingColors.recovery], ['Rest quality', 'Good sleep last night', RingColors.strain]] as const; const completed = habits.filter(Boolean).length; return <Page><Header eyebrow="Consistency" title="Daily journal" /><Card><View style={styles.ringsHeader}><View><Text style={styles.cardKicker}>MONTHLY CONSISTENCY</Text><Text style={styles.heroMetric}>{Math.round((completed / 3) * 100)}<Text style={styles.heroUnit}>%</Text></Text><Text style={styles.detail}>{completed} of 3 habits complete today</Text></View><View style={styles.ringStack}><View style={[styles.ringOuter, { borderColor: RingColors.protein }]}><View style={[styles.ringMiddle, { borderColor: RingColors.recovery }]}><View style={[styles.ringInner, { borderColor: RingColors.strain }]} /></View></View></View></View></Card><SectionTitle>Today&apos;s check-in</SectionTitle>{labels.map(([label, detail, color], index) => <Card key={label} style={styles.habitCard}><View style={[styles.habitIcon, { backgroundColor: `${color}22` }]}><Ionicons name={index === 0 ? 'restaurant-outline' : index === 1 ? 'barbell-outline' : 'moon-outline'} size={20} color={color} /></View><View style={styles.habitCopy}><Text style={styles.habitLabel}>{label}</Text><Text style={styles.detail}>{detail}</Text></View><Switch value={habits[index]} onValueChange={() => toggle(index)} trackColor={{ false: RingColors.border, true: color }} thumbColor={RingColors.text} /></Card>)}<SectionTitle>Correlation insight</SectionTitle><Card><Text style={styles.insight}>Protein + training days</Text><Text style={styles.insightBody}>Your overnight HRV is averaging <Text style={{ color: RingColors.recovery, fontWeight: '800' }}>+12 ms</Text> higher on days you complete both habits, leading to a <Text style={{ color: RingColors.recovery, fontWeight: '800' }}>+14%</Text> recovery lift.</Text></Card></Page>; }

export function SettingsScreen() { const { connected, battery, findMyRing, rawPacket } = useRingData(); return <Page><Header eyebrow="RingPulse" title="Settings" /><Card><SectionTitle>Device diagnostics</SectionTitle><View style={styles.settingLine}><Text style={styles.detail}>Connection</Text><Text style={{ color: connected ? RingColors.recovery : RingColors.muted, fontWeight: '800' }}>{connected ? 'Connected' : 'Disconnected'}</Text></View><View style={styles.settingLine}><Text style={styles.detail}>Battery</Text><Text style={styles.settingValue}>{battery}%</Text></View><View style={styles.settingLine}><Text style={styles.detail}>Firmware</Text><Text style={styles.settingValue}>R09 · 1.4.8</Text></View><View style={styles.settingLine}><Text style={styles.detail}>Bluetooth</Text><Text style={styles.settingValue}>COLMI R09</Text></View></Card><Card><SectionTitle>Ring controls</SectionTitle><Text style={styles.detail}>Optical LEDs will flash for 10 seconds.</Text><ActionButton label="Find my ring" icon="locate-outline" onPress={findMyRing} tone={RingColors.warning} /><View style={styles.buttonGap} /><ActionButton label="Sync local data" icon="cloud-upload-outline" tone={RingColors.strain} /></Card><Card><SectionTitle>Developer console <Text style={styles.detail}>raw BLE</Text></SectionTitle><View style={styles.console}><Text style={styles.consoleText}>{rawPacket}</Text><Text style={styles.consoleText}>service 6e40fff0... · TX notify</Text></View></Card></Page>; }